version: '3.7'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: COURS_DOCKER
      MARIADB_USER: adm
      MARIADB_PASSWORD: goToSleep
      MARIADB_ROOT_PASSWORD: Ethan
    volumes:
      - .:/code


  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:5000"
    environment:
      FLASK_DEBUG: "true"